language: node_js
node_js:
- 6.0
before_script:
  - npm install
  - npm install serverless -g
script:
  - npm test
deploy:
  - provider: script
    script: serverless deploy --stage prod
    on:
      branch: master
