language: node_js
node_js:
- 6.0
before_script:
  - npm install
  - npm install serverless -g
script:
  - npm run test:unit
  - npm run test:integration
  - npm run test:acceptance
  - npm run tag:success
deploy:
  - provider: script
    script: serverless deploy --stage prod
    on:
      branch: master
  - provider: script
    script: serverless deploy --stage staging
    on:
      branch: staging
