language: node_js
node_js: 6.10
before_install: npm install serverless -g

deploy:
  - provider: script
    skip_cleanup: true
    script: serverless deploy --stage prod --commit $TRAVIS_COMMIT
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: serverless deploy --stage staging --commit $TRAVIS_COMMIT
    on:
      branch: staging
