service: serverless-continuous-integration

custom:
  env_params: ${file(./serverless-env.yml):${opt:stage}}

provider:
  name: aws
  runtime: nodejs6.10

functions:
  greetings:
    handler: greetings.handler
    environment: ${self:custom.env_params}
    events:
      - http:
          path: greetings
          method: get
