service: serverless-continuous-integration

custom:
  environment: ${file(./serverless-env.yml)}
  env_params: ${self:custom.environment.${opt:stage}}
# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10

functions:
  greetings:
    handler: greetings.handler
    environment: ${self:custom.env_params}
    events:
      - http:
          path: greetings
          method: get
